### ISSUE TITLE
The social buttons are overlapping the content.

### ISSUE THREAD

**Issue by abstrxtInfinity** [Algo-Phantoms/Algo-Phantoms-Frontend#179]
The social site link icons are overlapping the content on a mobile device. I would like to fix this problem.
There is also the about text which has a blurred background for no reason.
You will find the screen shots attached.
Kindly assign me to this issue to work on.

![Screenshot_2021-03-16-21-35-17-756_com android chrome](https://user-images.githubusercontent.com/55052738/111342567-96556400-86a0-11eb-8cbb-a9a252fe9fe2.jpg)

![Screenshot_2021-03-16-21-35-31-028_com android chrome](https://user-images.githubusercontent.com/55052738/111342577-99505480-86a0-11eb-9378-6ec16957f359.jpg)

**Comment by abstrxtInfinity** [comment]
@Shruti3004 I am a participant of GSSOC'21 can you assign me this issue.

**Comment by ravikr126** [comment]
You can work now @abstrxtInfinity

**Comment by abstrxtInfinity** [comment]
fixed the social-sidebar overlaping in smaller devices #185

**Comment by AyushPradhan9** [comment]
The overlapping issue is still not solved, I can solve it if assigned to me. Thanks!

**Comment by abstrxtInfinity** [comment]
> The overlapping issue is still not solved, I can solve it if assigned to me. Thanks!

The changes have been staged and the pr is under review.

**Comment by ravikr126** [comment]
any progress @abstrxtInfinity ???

**Comment by abstrxtInfinity** [comment]
> any progress @abstrxtInfinity ???

#185 has been pushed for review **8 Days** Before.
